In [1]:
import pandas as pd

Location = "KickstarterComboPruned.csv"
df = pd.read_csv(Location)
df.head()

,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,state_recat,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
0,5971,An American Apocalypse: The Reckoning,Comics,Comics,US,failed,48000.0,376.0,USD,2012-06-08 18:46:56,2012-08-06,7,not_successful,1,0,376.00,1,0,0.007833,48000.000000
1,18520,Grandma's are Life,Music,World Music,US,failed,15000.0,62.0,USD,2016-10-19 15:32:00,2016-11-18 15:32:00,4,not_successful,1,0,62.00,1,0,0.004133,15000.000000
2,21109,Meta,Art,Performance Art,GB,successful,150.0,173.0,GBP,2015-04-08 00:37:44,2015-05-06,11,successful,0,1,258.04,0,1,1.153333,223.734104
3,21371,Water Powered Car,Technology,Technology,US,failed,75000.0,120.0,USD,2016-07-26 19:02:00,2016-08-10 19:02:00,4,not_successful,1,0,120.00,1,0,0.001600,75000.000000
4,24380,Puss N' Books: A relaxing cat cafe and bookstore.,Food,Spaces,US,failed,20000.0,776.0,USD,2015-10-27 16:25:33,2015-11-26,18,not_successful,1,0,776.00,1,0,0.038800,20000.000000

In [2]:
df.dtypes

ID                  int64
name               object
main_category      object
category           object
country            object
state              object
goal              float64
pledged           float64
currency           object
launched           object
deadline           object
backers             int64
state_recat        object
not_successful      int64
successful          int64
usd_pledged       float64
USD                 int64
not_USD             int64
ratio             float64
usd_goal          float64
dtype: object

In [3]:
df.count()

ID                366786
name              366785
main_category     366786
category          366786
country           366786
state             366786
goal              366786
pledged           366786
currency          366786
launched          366786
deadline          366786
backers           366786
state_recat       366786
not_successful    366786
successful        366786
usd_pledged       366786
USD               366786
not_USD           366786
ratio             366786
usd_goal          366786
dtype: int64

In [4]:
df.describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,3.667860e+05,3.667860e+05,3.667860e+05,366786.000000,366786.000000,366786.000000,3.667860e+05,366786.000000,366786.000000,366786.000000,3.667860e+05
mean,1.072195e+09,4.648947e+04,9.811197e+03,107.836362,0.635161,0.364839,8.703158e+03,0.787334,0.212666,3.291755,4.639099e+04
std,6.193353e+08,1.110611e+06,9.670281e+04,918.367627,0.481386,0.481386,9.053174e+04,0.409194,0.409194,270.932060,1.136660e+06
min,5.971000e+03,1.000000e-02,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,1.000000e-02
25%,5.349251e+08,2.000000e+03,3.500000e+01,2.000000,0.000000,0.000000,2.792000e+01,1.000000,0.000000,0.005000,2.000000e+03
50%,1.071315e+09,5.250000e+03,6.400000e+02,13.000000,1.000000,0.000000,5.550000e+02,1.000000,0.000000,0.140000,5.000000e+03
75%,1.607617e+09,1.600000e+04,4.135000e+03,58.000000,1.000000,1.000000,3.750000e+03,1.000000,0.000000,1.068000,1.500000e+04
max,2.147476e+09,1.000000e+08,2.033899e+07,219382.000000,1.000000,1.000000,2.033899e+07,1.000000,1.000000,104277.890000,1.320130e+08

In [5]:
pd.value_counts(df['main_category'])

Film & Video      61156
Music             48739
Publishing        38586
Games             34370
Technology        31630
Design            29457
Art               27607
Food              24082
Fashion           22285
Theater           10704
Comics            10650
Photography       10571
Crafts             8601
Journalism         4637
Dance              3710
Graphic Novels        1
Name: main_category, dtype: int64

In [6]:
pd.value_counts(df['category'])

Product Design       21863
Documentary          15899
Tabletop Games       13909
Music                13121
Shorts               11966
Video Games          11504
Food                 11300
Film & Video          8992
Fiction               8977
Fashion               8444
Nonfiction            8195
Art                   8079
Theater               6972
Apparel               6969
Technology            6752
Rock                  6666
Children's Books      6664
Apps                  6077
Webseries             5686
Photography           5662
Indie Rock            5618
Publishing            5381
Narrative Film        5120
Web                   4977
Comics                4957
Crafts                4566
Country & Folk        4415
Design                4115
Hip-Hop               3823
Hardware              3616
                     ...
Couture                261
Animals                248
Fabrication Tools      242
Printing               233
Makerspaces            230
Puzzles                227
Movie Theaters         226
Bacon                  213
Stationery             211
Photo                  191
Video Art              188
Knitting               180
Romance                179
Crochet                160
Workshops              159
Translations           141
Pet Fashion            139
Glass                  137
Latin                  121
Embroidery             111
Typography             105
Pottery                 96
Weaving                 87
Quilts                  81
Residencies             67
Letterpress             48
Chiptune                35
Literary Spaces         23
Taxidermy               13
 Religion                1
Name: category, Length: 160, dtype: int64

## MUSIC (Main_Category)

In [7]:
dfmusic = df
dfmusic = dfmusic.drop(dfmusic[dfmusic['main_category']!='Music'].index)
dfmusic.head()

,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,state_recat,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
1,18520,Grandma's are Life,Music,World Music,US,failed,15000.0,62.00,USD,2016-10-19 15:32:00,2016-11-18 15:32:00,4,not_successful,1,0,62.00,1,0,0.004133,15000.0
11,52687,Revenge of the Platypus,Music,Electronic Music,US,successful,1200.0,1201.00,USD,2012-11-22 01:39:32,2012-12-22,25,successful,0,1,1201.00,1,0,1.000833,1200.0
18,106144,"Robert Cooper Music's New Album ""Wayward Pines""",Music,Music,US,failed,1800.0,15.00,USD,2014-05-16 00:36:00,2014-06-15 00:36:00,1,not_successful,1,0,15.00,1,0,0.008333,1800.0
30,197154,North Eugene High School Ukulele Orchestra's F...,Music,Indie Rock,US,successful,1450.0,1593.99,USD,2013-01-11 17:49:37,2013-02-10,79,successful,0,1,1593.99,1,0,1.099303,1450.0
74,436325,Music - Comedy - Album!,Music,Music,US,successful,1000.0,1125.00,USD,2010-02-09 17:21:30,2010-04-18,30,successful,0,1,1125.00,1,0,1.125000,1000.0

In [8]:
pd.value_counts(dfmusic['category'])

Music               13121
Rock                 6666
Indie Rock           5618
Country & Folk       4415
Hip-Hop              3823
Pop                  3285
Classical Music      2574
Electronic Music     2115
World Music          2062
Jazz                 1827
Faith                1065
Metal                 701
R&B                   447
Punk                  310
Kids                  275
Blues                 261
Latin                 121
Chiptune               35
Comedy                 18
Name: category, dtype: int64

In [9]:
dfmusic.describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,4.873900e+04,4.873900e+04,4.873900e+04,48739.000000,48739.000000,48739.000000,4.873900e+04,48739.000000,48739.000000,48739.000000,4.873900e+04
mean,1.072774e+09,1.612264e+04,4.059568e+03,55.229775,0.506596,0.493404,3.854083e+03,0.878516,0.121484,8.307077,1.593968e+04
std,6.190072e+08,3.618146e+05,1.459112e+04,203.839604,0.499962,0.499962,1.314960e+04,0.326692,0.326692,638.888249,3.623005e+05
min,1.852000e+04,1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,2.712195e-02
25%,5.349644e+08,1.500000e+03,5.000000e+01,2.000000,0.000000,0.000000,4.593874e+01,1.000000,0.000000,0.013439,1.500000e+03
50%,1.067964e+09,4.000000e+03,1.016000e+03,19.000000,1.000000,0.000000,9.400000e+02,1.000000,0.000000,0.601667,4.000000e+03
75%,1.609590e+09,1.000000e+04,4.204500e+03,62.000000,1.000000,1.000000,4.080000e+03,1.000000,0.000000,1.104000,9.092001e+03
max,2.147472e+09,5.000000e+07,1.363037e+06,24883.000000,1.000000,1.000000,1.363037e+06,1.000000,1.000000,104277.890000,5.000000e+07

In [10]:
print(dfmusic[dfmusic['category']=='Music']['successful'].mean())

0.4817468180778904

In [11]:
print(dfmusic[dfmusic['category']=='Rock']['successful'].mean())

0.5243024302430243

In [12]:
print(dfmusic[dfmusic['category']=='Indie Rock']['successful'].mean())

0.6422214311142755

In [13]:
print(dfmusic[dfmusic['category']=='Country & Folk']['successful'].mean())

0.6355605889014723

In [14]:
print(dfmusic[dfmusic['category']=='Hip-Hop']['successful'].mean())

0.15772953178132357

In [15]:
print(dfmusic[dfmusic['category']=='Pop']['successful'].mean())

0.4727549467275495

In [16]:
print(dfmusic[dfmusic['category']=='Classical Music']['successful'].mean())

0.6390831390831391

In [17]:
print(dfmusic[dfmusic['category']=='Electronic Music']['successful'].mean())

0.33144208037825057

In [18]:
print(dfmusic[dfmusic['category']=='World Music']['successful'].mean())

0.44713870029097963

In [19]:
print(dfmusic[dfmusic['category']=='Jazz']['successful'].mean())

0.6026272577996716

In [20]:
print(dfmusic[dfmusic['category']=='Faith']['successful'].mean())

0.4253521126760563

In [21]:
dfmusic.corr()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
ID,1.000000,0.002918,-0.002712,-0.001649,-0.002309,0.002309,-0.000710,0.001896,-0.001896,-0.003031,0.003479
goal,0.002918,1.000000,0.022475,0.005545,0.027843,-0.027843,0.008788,-0.002945,0.002945,-0.000562,0.995655
pledged,-0.002712,0.022475,1.000000,0.805656,-0.234805,0.234805,0.907699,0.007261,-0.007261,0.041641,0.007439
backers,-0.001649,0.005545,0.805656,1.000000,-0.229354,0.229354,0.861810,0.025516,-0.025516,0.092599,0.003367
not_successful,-0.002309,0.027843,-0.234805,-0.229354,1.000000,-1.000000,-0.250385,-0.070026,0.070026,-0.013041,0.028069
successful,0.002309,-0.027843,0.234805,0.229354,-1.000000,1.000000,0.250385,0.070026,-0.070026,0.013041,-0.028069
usd_pledged,-0.000710,0.008788,0.907699,0.861810,-0.250385,0.250385,1.000000,0.050080,-0.050080,0.046300,0.007222
USD,0.001896,-0.002945,0.007261,0.025516,-0.070026,0.070026,0.050080,1.000000,-1.000000,0.003313,-0.001583
not_USD,-0.001896,0.002945,-0.007261,-0.025516,0.070026,-0.070026,-0.050080,-1.000000,1.000000,-0.003313,0.001583
ratio,-0.003031,-0.000562,0.041641,0.092599,-0.013041,0.013041,0.046300,0.003313,-0.003313,1.000000,-0.000555
usd_goal,0.003479,0.995655,0.007439,0.003367,0.028069,-0.028069,0.007222,-0.001583,0.001583,-0.000555,1.000000

In [22]:
dfmusic[dfmusic['successful']==1].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,2.404800e+04,24048.000000,2.404800e+04,24048.000000,24048.0,24048.0,2.404800e+04,24048.000000,24048.000000,24048.000000,24048.000000
mean,1.074222e+09,5915.119330,7.531098e+03,102.601672,0.0,1.0,7.190237e+03,0.901697,0.098303,16.749692,5635.198018
std,6.196494e+08,10067.544865,1.879128e+04,280.979645,0.0,0.0,1.793582e+04,0.297731,0.297731,909.476245,8620.982214
min,5.268700e+04,1.000000,1.000000e+00,1.000000,0.0,1.0,0.000000e+00,0.000000,0.000000,1.000000,0.027122
25%,5.373128e+08,1500.000000,1.817245e+03,32.000000,0.0,1.0,1.680000e+03,1.000000,0.000000,1.035891,1400.000000
50%,1.071597e+09,3017.000000,3.927500e+03,60.000000,0.0,1.0,3.769495e+03,1.000000,0.000000,1.106710,3000.000000
75%,1.609933e+09,7000.000000,8.285000e+03,108.000000,0.0,1.0,8.110500e+03,1.000000,0.000000,1.292252,7000.000000
max,2.147472e+09,500000.000000,1.363037e+06,24883.000000,0.0,1.0,1.363037e+06,1.000000,1.000000,104277.890000,250000.000000

In [23]:
print(len(dfmusic[(dfmusic['successful']==1) & (dfmusic['usd_goal']>=100000)]))

31

In [24]:
print(len(dfmusic[(dfmusic['successful']==1) & (dfmusic['usd_goal']>=150000)]))

11

In [25]:
print(len(dfmusic[(dfmusic['successful']==1) & (dfmusic['usd_goal']>=200000)]))

4

In [26]:
dfmusic[(dfmusic['successful']==1) & (dfmusic['usd_goal']>=200000)].head()

,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,state_recat,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
147960,864588968,New Carman Album and Music Video,Music,Faith,US,successful,200000.0,538103.02,USD,2013-04-20 05:11:38,2013-06-19,5043,successful,0,1,538103.0200,1,0,2.690515,200000.000000
254928,1489765898,Smithsonian Anthology of Hip-Hop and Rap,Music,Hip-Hop,US,successful,250000.0,368841.00,USD,2017-10-17 11:00:29,2017-11-16,2804,successful,0,1,368841.0000,1,0,1.475364,250000.000000
270139,1578567890,Foo For The Fans - No More Touts (Canceled),Music,Rock,GB,canceled,150000.0,150245.02,GBP,2014-09-19 20:32:00,2014-11-18 20:32:00,1335,successful,0,1,244474.1637,0,1,1.001633,244075.474548
315564,1845154468,Electronic Opus,Music,Electronic Music,US,successful,200000.0,254767.00,USD,2014-11-10 18:00:00,2014-12-10 18:00:00,2117,successful,0,1,254767.0000,1,0,1.273835,200000.000000

In [27]:
import statsmodels.formula.api as sm
result = sm.ols(formula='successful ~ usd_goal + usd_pledged + backers + USD - 1', data=dfmusic).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.493
Model:                            OLS   Adj. R-squared:                  0.493
Method:                 Least Squares   F-statistic:                 1.183e+04
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:46   Log-Likelihood:                -35408.
No. Observations:               48739   AIC:                         7.082e+04
Df Residuals:                   48735   BIC:                         7.086e+04
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
usd_goal    -3.481e-08   6.26e-09     -5.566      0.000   -4.71e-08   -2.26e-08
usd_pledged   7.35e-06    3.4e-07     21.598      0.000    6.68e-06    8.02e-06
backers         0.0002   2.19e-05      8.938      0.000       0.000       0.000
USD             0.4656      0.003    184.682      0.000       0.461       0.471
==============================================================================
Omnibus:                    13287.262   Durbin-Watson:                   1.977
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           472303.442
Skew:                          -0.638   Prob(JB):                         0.00
Kurtosis:                      18.197   Cond. No.                     4.03e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.03e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [28]:
import statsmodels.formula.api as sm
result = sm.ols(formula='successful ~ usd_pledged + backers + USD + usd_pledged*backers + usd_goal*backers - 1', data=dfmusic).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.533
Model:                            OLS   Adj. R-squared:                  0.533
Method:                 Least Squares   F-statistic:                     9263.
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:46   Log-Likelihood:                -33397.
No. Observations:               48739   AIC:                         6.681e+04
Df Residuals:                   48733   BIC:                         6.686e+04
Df Model:                           6
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
usd_pledged          1.273e-05   3.42e-07     37.286      0.000    1.21e-05    1.34e-05
backers                 0.0007   2.27e-05     31.634      0.000       0.001       0.001
USD                     0.4199      0.003    166.610      0.000       0.415       0.425
usd_pledged:backers -1.049e-09   2.21e-11    -47.474      0.000   -1.09e-09   -1.01e-09
usd_goal            -1.295e-08   6.07e-09     -2.134      0.033   -2.48e-08   -1.06e-09
usd_goal:backers    -3.055e-09   1.22e-10    -25.008      0.000   -3.29e-09   -2.82e-09
==============================================================================
Omnibus:                     5042.822   Durbin-Watson:                   1.971
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            43563.616
Skew:                           0.043   Prob(JB):                         0.00
Kurtosis:                       7.631   Cond. No.                     1.81e+08
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.81e+08. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## INDIE ROCK (Category under Music)

In [29]:
dfmusic[dfmusic['category']=='Indie Rock'].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,5.618000e+03,5.618000e+03,5618.000000,5618.000000,5618.000000,5618.000000,5618.000000,5618.000000,5618.000000,5618.000000,5.618000e+03
mean,1.081038e+09,6.084059e+03,3949.269258,61.471164,0.357779,0.642221,3889.145354,0.939480,0.060520,2.200960,6.075966e+03
std,6.122453e+08,3.392036e+04,8922.501955,135.640601,0.479389,0.479389,8707.302265,0.238469,0.238469,49.190583,3.814053e+04
min,1.971540e+05,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00
25%,5.521445e+08,1.500000e+03,368.250000,9.000000,0.000000,0.000000,340.000000,1.000000,0.000000,0.148443,1.500000e+03
50%,1.084699e+09,3.000000e+03,1790.000000,33.000000,0.000000,1.000000,1756.375000,1.000000,0.000000,1.033283,3.000000e+03
75%,1.609004e+09,6.000000e+03,4637.500000,71.000000,1.000000,1.000000,4565.000000,1.000000,0.000000,1.175000,6.000000e+03
max,2.147422e+09,1.957167e+06,278486.000000,3305.000000,1.000000,1.000000,278486.000000,1.000000,1.000000,2750.260000,2.283759e+06

In [30]:
dfmusic[dfmusic['category']=='Indie Rock'].corr()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
ID,1.000000,-0.015417,-0.006633,-0.013822,0.009825,-0.009825,-0.010746,0.006450,-0.006450,-0.004849,-0.015818
goal,-0.015417,1.000000,0.137113,0.098114,0.061876,-0.061876,0.129900,-0.064485,0.064485,-0.005659,0.994622
pledged,-0.006633,0.137113,1.000000,0.873726,-0.270484,0.270484,0.972484,0.036205,-0.036205,0.001295,0.112158
backers,-0.013822,0.098114,0.873726,1.000000,-0.272454,0.272454,0.895284,0.050340,-0.050340,0.007745,0.086781
not_successful,0.009825,0.061876,-0.270484,-0.272454,1.000000,-1.000000,-0.274912,-0.064403,0.064403,-0.031521,0.056490
successful,-0.009825,-0.061876,0.270484,0.272454,-1.000000,1.000000,0.274912,0.064403,-0.064403,0.031521,-0.056490
usd_pledged,-0.010746,0.129900,0.972484,0.895284,-0.274912,0.274912,1.000000,0.064307,-0.064307,0.001544,0.115697
USD,0.006450,-0.064485,0.036205,0.050340,-0.064403,0.064403,0.064307,1.000000,-1.000000,0.000997,-0.056514
not_USD,-0.006450,0.064485,-0.036205,-0.050340,0.064403,-0.064403,-0.064307,-1.000000,1.000000,-0.000997,0.056514
ratio,-0.004849,-0.005659,0.001295,0.007745,-0.031521,0.031521,0.001544,0.000997,-0.000997,1.000000,-0.005052
usd_goal,-0.015818,0.994622,0.112158,0.086781,0.056490,-0.056490,0.115697,-0.056514,0.056514,-0.005052,1.000000

In [31]:
dfmusic[(dfmusic['category']=='Indie Rock') & (dfmusic['successful']==1)].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,3.608000e+03,3608.000000,3608.000000,3608.000000,3608.0,3608.0,3608.000000,3608.000000,3608.000000,3608.000000,3608.000000
mean,1.076549e+09,4517.632614,5750.439745,89.052106,0.0,1.0,5675.644354,0.950942,0.049058,3.358143,4467.977365
std,6.172556e+08,6892.735938,10597.206101,161.206138,0.0,0.0,10334.137763,0.216018,0.216018,61.354212,6736.076733
min,1.971540e+05,1.000000,12.000000,1.000000,0.0,1.0,0.000000,0.000000,0.000000,1.000000,1.000000
25%,5.344180e+08,1200.000000,1620.000000,31.000000,0.0,1.0,1606.750000,1.000000,0.000000,1.039500,1200.000000
50%,1.069153e+09,2815.500000,3230.995000,55.000000,0.0,1.0,3236.500000,1.000000,0.000000,1.118663,2832.927202
75%,1.618473e+09,5000.000000,6330.245000,96.000000,0.0,1.0,6301.750000,1.000000,0.000000,1.317246,5000.000000
max,2.147422e+09,150000.000000,278486.000000,3305.000000,0.0,1.0,278486.000000,1.000000,1.000000,2750.260000,150000.000000

In [32]:
result = sm.ols(formula='successful ~ usd_goal + usd_pledged + backers + USD - 1', data=dfmusic[dfmusic['category']=='Indie Rock']).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.650
Model:                            OLS   Adj. R-squared:                  0.650
Method:                 Least Squares   F-statistic:                     2608.
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:47   Log-Likelihood:                -3777.9
No. Observations:                5618   AIC:                             7564.
Df Residuals:                    5614   BIC:                             7590.
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
usd_goal    -7.679e-07   1.67e-07     -4.604      0.000   -1.09e-06   -4.41e-07
usd_pledged    8.4e-06   1.64e-06      5.127      0.000    5.19e-06    1.16e-05
backers         0.0005      0.000      5.234      0.000       0.000       0.001
USD             0.5858      0.007     81.190      0.000       0.572       0.600
==============================================================================
Omnibus:                      255.296   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              279.673
Skew:                          -0.530   Prob(JB):                     1.86e-61
Kurtosis:                       2.733   Cond. No.                     4.41e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.41e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
result = sm.ols(formula='successful ~ usd_goal + usd_pledged + backers + USD + usd_pledged*backers - 1', data=dfmusic[dfmusic['category']=='Indie Rock']).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.683
Model:                            OLS   Adj. R-squared:                  0.683
Method:                 Least Squares   F-statistic:                     2421.
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:47   Log-Likelihood:                -3499.0
No. Observations:                5618   AIC:                             7008.
Df Residuals:                    5613   BIC:                             7041.
Df Model:                           5
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
usd_goal                -8e-07   1.59e-07     -5.039      0.000   -1.11e-06   -4.89e-07
usd_pledged           2.06e-05   1.64e-06     12.572      0.000    1.74e-05    2.38e-05
backers                 0.0012      0.000     12.009      0.000       0.001       0.001
USD                     0.5121      0.008     68.167      0.000       0.497       0.527
usd_pledged:backers -1.414e-08   5.84e-10    -24.206      0.000   -1.53e-08    -1.3e-08
==============================================================================
Omnibus:                       59.995   Durbin-Watson:                   1.967
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               59.646
Skew:                          -0.234   Prob(JB):                     1.12e-13
Kurtosis:                       2.812   Cond. No.                     2.16e+07
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.16e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## CLASSICAL MUSIC (Category under Music)

In [34]:
dfmusic[dfmusic['category']=='Classical Music'].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,2.574000e+03,2.574000e+03,2.574000e+03,2574.000000,2574.000000,2574.000000,2574.000000,2574.000000,2574.000000,2574.000000,2.574000e+03
mean,1.048709e+09,1.020019e+04,5.190531e+03,54.281274,0.360917,0.639083,4432.395893,0.836830,0.163170,1.079545,9.311400e+03
std,6.250274e+08,6.830946e+04,2.349523e+04,141.140948,0.480360,0.480360,8245.176930,0.369593,0.369593,6.546352,5.570717e+04
min,6.597960e+05,1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00
25%,4.840916e+08,2.000000e+03,5.200000e+02,9.000000,0.000000,0.000000,421.237500,1.000000,0.000000,0.133906,1.761996e+03
50%,1.063319e+09,4.000000e+03,2.190500e+03,30.000000,0.000000,1.000000,2099.500000,1.000000,0.000000,1.025000,4.000000e+03
75%,1.578336e+09,8.000000e+03,5.525000e+03,66.000000,1.000000,1.000000,5444.000000,1.000000,0.000000,1.130165,8.000000e+03
max,2.147431e+09,3.000000e+06,1.058547e+06,4256.000000,1.000000,1.000000,174012.117300,1.000000,1.000000,280.142667,2.657000e+06

In [35]:
dfmusic[dfmusic['category']=='Classical Music'].corr()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
ID,1.000000,-0.011214,-0.005538,0.007670,-0.021021,0.021021,0.008334,0.008489,-0.008489,0.047788,-0.027511
goal,-0.011214,1.000000,0.884326,0.295337,0.084434,-0.084434,0.402432,-0.073764,0.073764,-0.013022,0.222744
pledged,-0.005538,0.884326,1.000000,0.539258,-0.093067,0.093067,0.669044,-0.054704,0.054704,0.008324,0.170923
backers,0.007670,0.295337,0.539258,1.000000,-0.215662,0.215662,0.750996,0.007630,-0.007630,0.047918,0.073716
not_successful,-0.021021,0.084434,-0.093067,-0.215662,1.000000,-1.000000,-0.305653,-0.075339,0.075339,-0.110063,0.092699
successful,0.021021,-0.084434,0.093067,0.215662,-1.000000,1.000000,0.305653,0.075339,-0.075339,0.110063,-0.092699
usd_pledged,0.008334,0.402432,0.669044,0.750996,-0.305653,0.305653,1.000000,0.052388,-0.052388,0.029512,0.122772
USD,0.008489,-0.073764,-0.054704,0.007630,-0.075339,0.075339,0.052388,1.000000,-1.000000,0.024938,-0.054313
not_USD,-0.008489,0.073764,0.054704,-0.007630,0.075339,-0.075339,-0.052388,-1.000000,1.000000,-0.024938,0.054313
ratio,0.047788,-0.013022,0.008324,0.047918,-0.110063,0.110063,0.029512,0.024938,-0.024938,1.000000,-0.015358
usd_goal,-0.027511,0.222744,0.170923,0.073716,0.092699,-0.092699,0.122772,-0.054313,0.054313,-0.015358,1.000000

In [36]:
dfmusic[(dfmusic['category']=='Classical Music') & (dfmusic['successful']==1)].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,1.645000e+03,1645.000000,1645.000000,1645.000000,1645.0,1645.0,1645.000000,1645.000000,1645.000000,1645.000000,1645.000000
mean,1.058580e+09,5866.713070,6833.455994,77.151368,0.0,1.0,6325.910284,0.857751,0.142249,1.620901,5431.455402
std,6.277447e+08,10191.461462,12044.514769,163.027320,0.0,0.0,8711.746032,0.349412,0.349412,8.138986,6781.239627
min,9.826290e+05,1.000000,6.000000,1.000000,0.0,1.0,0.000000,0.000000,0.000000,1.000000,1.000000
25%,4.911039e+08,1635.000000,2055.000000,28.000000,0.0,1.0,2000.000000,1.000000,0.000000,1.030000,1500.000000
50%,1.077733e+09,3500.000000,4058.000000,52.000000,0.0,1.0,4012.000000,1.000000,0.000000,1.086667,3500.000000
75%,1.584070e+09,7000.000000,7825.000000,87.000000,0.0,1.0,7645.000000,1.000000,0.000000,1.232704,7000.000000
max,2.147431e+09,250000.000000,264967.000000,4256.000000,0.0,1.0,140005.210000,1.000000,1.000000,280.142667,100000.000000

In [37]:
result = sm.ols(formula='successful ~ usd_goal + usd_pledged + USD + ratio - 1', data=dfmusic[dfmusic['category']=='Classical Music']).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.620
Model:                            OLS   Adj. R-squared:                  0.620
Method:                 Least Squares   F-statistic:                     1050.
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:48   Log-Likelihood:                -1829.3
No. Observations:                2574   AIC:                             3667.
Df Residuals:                    2570   BIC:                             3690.
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
usd_goal    -7.499e-07   1.75e-07     -4.278      0.000   -1.09e-06   -4.06e-07
usd_pledged  2.212e-05   1.18e-06     18.808      0.000    1.98e-05    2.44e-05
USD             0.5491      0.012     45.689      0.000       0.526       0.573
ratio           0.0084      0.001      5.649      0.000       0.005       0.011
==============================================================================
Omnibus:                      114.351   Durbin-Watson:                   1.989
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              149.050
Skew:                          -0.448   Prob(JB):                     4.31e-33
Kurtosis:                       3.765   Cond. No.                     6.99e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.99e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [38]:
result = sm.ols(formula='successful ~ usd_goal + usd_pledged + backers + USD + ratio + usd_pledged*backers - 1', data=dfmusic[dfmusic['category']=='Classical Music']).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.674
Model:                            OLS   Adj. R-squared:                  0.674
Method:                 Least Squares   F-statistic:                     886.3
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:48   Log-Likelihood:                -1632.2
No. Observations:                2574   AIC:                             3276.
Df Residuals:                    2568   BIC:                             3312.
Df Model:                           6
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
usd_goal            -5.265e-07   1.63e-07     -3.232      0.001   -8.46e-07   -2.07e-07
usd_pledged          2.546e-05   1.67e-06     15.271      0.000    2.22e-05    2.87e-05
backers                 0.0021      0.000     14.540      0.000       0.002       0.002
USD                     0.4469      0.012     36.648      0.000       0.423       0.471
ratio                   0.0077      0.001      5.558      0.000       0.005       0.010
usd_pledged:backers -2.554e-08   1.24e-09    -20.601      0.000    -2.8e-08   -2.31e-08
==============================================================================
Omnibus:                       36.490   Durbin-Watson:                   1.981
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               36.279
Skew:                          -0.269   Prob(JB):                     1.32e-08
Kurtosis:                       2.779   Cond. No.                     1.96e+07
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.96e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## VIDEO GAMES (Category under Games)

In [39]:
dfvideogames = df
dfvideogames = dfvideogames.drop(dfvideogames[dfvideogames['category']!='Video Games'].index)
dfvideogames.head()

,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,state_recat,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
28,188667,Last-Wars,Games,Video Games,CA,failed,35000.0,621.00,CAD,2015-04-05 21:53:00,2015-05-10 21:53:00,6,not_successful,1,0,497.043351,0,1,0.017743,28013.715452
185,1058397,Mystery World Dizzy - A 'new' old game by The ...,Games,Video Games,GB,successful,12500.0,28016.00,GBP,2017-10-15 17:16:04,2017-11-14,483,successful,0,1,19038.890000,0,1,2.241280,8494.650378
190,1086007,Melee Masters,Games,Video Games,US,canceled,125000.0,360.00,USD,2017-03-10 13:20:43,2017-04-09,6,not_successful,1,0,360.000000,1,0,0.002880,125000.000000
244,1394048,Out of Sync Cup - ZeroEmpires,Games,Video Games,GB,successful,120.0,316.12,GBP,2014-02-07 00:26:18,2014-02-28,16,successful,0,1,516.130000,0,1,2.634333,195.924333
249,1403417,Liora - RPG meets Tower Defense/Castle Defense,Games,Video Games,CA,failed,25000.0,6722.00,CAD,2013-09-26 19:22:52,2013-11-05,57,not_successful,1,0,6526.750000,0,1,0.268880,24273.839631

In [40]:
dfvideogames.describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,1.150400e+04,1.150400e+04,1.150400e+04,11504.000000,11504.000000,11504.000000,1.150400e+04,11504.000000,11504.000000,11504.000000,1.150400e+04
mean,1.070730e+09,7.811050e+04,1.839227e+04,378.282684,0.791551,0.208449,1.772766e+04,0.663334,0.336666,6.818652,7.624479e+04
std,6.188462e+08,1.134065e+06,1.469071e+05,2513.751598,0.406217,0.406217,1.500232e+05,0.472590,0.472590,423.684601,1.125602e+06
min,1.886670e+05,1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,8.918919e-02
25%,5.328705e+08,3.287500e+03,4.100000e+01,3.000000,1.000000,0.000000,3.300000e+01,0.000000,0.000000,0.004444,3.000000e+03
50%,1.066891e+09,1.000000e+04,4.300000e+02,13.000000,1.000000,0.000000,3.512585e+02,1.000000,0.000000,0.052236,1.000000e+04
75%,1.605056e+09,4.000000e+04,4.309438e+03,90.000000,1.000000,0.000000,3.730050e+03,1.000000,1.000000,0.408927,3.600000e+04
max,2.147161e+09,1.000000e+08,6.333296e+06,87142.000000,1.000000,1.000000,6.333296e+06,1.000000,1.000000,41535.010000,1.000000e+08

In [41]:
dfvideogames.corr()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
ID,1.000000,-0.005117,-0.004238,-0.003803,-0.003864,0.003864,-0.006469,0.013389,-0.013389,0.011866,-0.005079
goal,-0.005117,1.000000,0.038504,0.031735,0.018624,-0.018624,0.036668,0.011149,-0.011149,-0.001070,0.993650
pledged,-0.004238,0.038504,1.000000,0.916124,-0.195150,0.195150,0.989827,0.039779,-0.039779,0.001786,0.037628
backers,-0.003803,0.031735,0.916124,1.000000,-0.239291,0.239291,0.924407,0.036717,-0.036717,0.004508,0.032996
not_successful,-0.003864,0.018624,-0.195150,-0.239291,1.000000,-1.000000,-0.186858,-0.039997,0.039997,-0.030948,0.018492
successful,0.003864,-0.018624,0.195150,0.239291,-1.000000,1.000000,0.186858,0.039997,-0.039997,0.030948,-0.018492
usd_pledged,-0.006469,0.036668,0.989827,0.924407,-0.186858,0.186858,1.000000,0.045171,-0.045171,0.001791,0.038666
USD,0.013389,0.011149,0.039779,0.036717,-0.039997,0.039997,0.045171,1.000000,-1.000000,0.002719,0.013559
not_USD,-0.013389,-0.011149,-0.039779,-0.036717,0.039997,-0.039997,-0.045171,-1.000000,1.000000,-0.002719,-0.013559
ratio,0.011866,-0.001070,0.001786,0.004508,-0.030948,0.030948,0.001791,0.002719,-0.002719,1.000000,-0.001053
usd_goal,-0.005079,0.993650,0.037628,0.032996,0.018492,-0.018492,0.038666,0.013559,-0.013559,-0.001053,1.000000

In [42]:
dfvideogames[dfvideogames['successful']==1].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,2.398000e+03,2.398000e+03,2.398000e+03,2398.000000,2398.0,2398.0,2.398000e+03,2398.000000,2398.000000,2398.000000,2.398000e+03
mean,1.075389e+09,3.695479e+04,7.425615e+04,1550.396997,0.0,1.0,7.235249e+04,0.700167,0.299833,32.368628,3.568534e+04
std,6.145491e+08,1.183519e+05,3.135701e+05,5310.569968,0.0,0.0,3.211875e+05,0.458280,0.458280,927.696947,1.230581e+05
min,1.058397e+06,1.000000e+00,3.000000e+00,1.000000,0.0,1.0,0.000000e+00,0.000000,0.000000,1.000000,8.918919e-02
25%,5.380320e+08,1.500000e+03,2.783767e+03,68.000000,0.0,1.0,1.961463e+03,0.000000,0.000000,1.100115,1.000000e+03
50%,1.088288e+09,7.500000e+03,1.118326e+04,282.500000,0.0,1.0,9.790830e+03,1.000000,0.000000,1.328159,6.000000e+03
75%,1.595449e+09,2.500000e+04,4.173957e+04,1123.500000,0.0,1.0,3.651136e+04,1.000000,1.000000,2.124136,2.346325e+04
max,2.147161e+09,2.000000e+06,6.333296e+06,87142.000000,0.0,1.0,6.333296e+06,1.000000,1.000000,41535.010000,2.003273e+06

In [43]:
result = sm.ols(formula='successful ~ usd_pledged + backers + ratio  + USD - 1', data=dfvideogames).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.214
Model:                            OLS   Adj. R-squared:                  0.214
Method:                 Least Squares   F-statistic:                     783.2
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:50   Log-Likelihood:                -5918.2
No. Observations:               11504   AIC:                         1.184e+04
Df Residuals:                   11500   BIC:                         1.187e+04
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
usd_pledged  -7.42e-07   6.59e-08    -11.260      0.000   -8.71e-07   -6.13e-07
backers      8.165e-05   3.93e-06     20.793      0.000     7.4e-05    8.93e-05
ratio        2.954e-05   8.91e-06      3.316      0.001    1.21e-05     4.7e-05
USD             0.2003      0.005     42.759      0.000       0.191       0.209
==============================================================================
Omnibus:                     2036.462   Durbin-Watson:                   1.940
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3483.041
Skew:                           1.162   Prob(JB):                         0.00
Kurtosis:                       4.366   Cond. No.                     1.87e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.87e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [44]:
result = sm.ols(formula='successful ~ usd_pledged + backers + ratio  + USD + usd_pledged*backers - 1', data=dfvideogames).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.257
Model:                            OLS   Adj. R-squared:                  0.257
Method:                 Least Squares   F-statistic:                     796.4
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:50   Log-Likelihood:                -5593.7
No. Observations:               11504   AIC:                         1.120e+04
Df Residuals:                   11499   BIC:                         1.123e+04
Df Model:                           5
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
usd_pledged          2.641e-07    7.5e-08      3.523      0.000    1.17e-07    4.11e-07
backers              9.802e-05   3.87e-06     25.329      0.000    9.04e-05       0.000
ratio                2.836e-05   8.66e-06      3.274      0.001    1.14e-05    4.53e-05
USD                     0.1823      0.005     39.573      0.000       0.173       0.191
usd_pledged:backers -2.517e-11   9.74e-13    -25.837      0.000   -2.71e-11   -2.33e-11
==============================================================================
Omnibus:                     2329.687   Durbin-Watson:                   1.941
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4044.305
Skew:                           1.341   Prob(JB):                         0.00
Kurtosis:                       4.115   Cond. No.                     1.06e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.06e+10. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [45]:
dfvideogames2 = dfvideogames
dfvideogames2 = dfvideogames2.drop(dfvideogames2[dfvideogames2['usd_goal']>2500000].index)
dfvideogames2.head()

,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,state_recat,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
28,188667,Last-Wars,Games,Video Games,CA,failed,35000.0,621.00,CAD,2015-04-05 21:53:00,2015-05-10 21:53:00,6,not_successful,1,0,497.043351,0,1,0.017743,28013.715452
185,1058397,Mystery World Dizzy - A 'new' old game by The ...,Games,Video Games,GB,successful,12500.0,28016.00,GBP,2017-10-15 17:16:04,2017-11-14,483,successful,0,1,19038.890000,0,1,2.241280,8494.650378
190,1086007,Melee Masters,Games,Video Games,US,canceled,125000.0,360.00,USD,2017-03-10 13:20:43,2017-04-09,6,not_successful,1,0,360.000000,1,0,0.002880,125000.000000
244,1394048,Out of Sync Cup - ZeroEmpires,Games,Video Games,GB,successful,120.0,316.12,GBP,2014-02-07 00:26:18,2014-02-28,16,successful,0,1,516.130000,0,1,2.634333,195.924333
249,1403417,Liora - RPG meets Tower Defense/Castle Defense,Games,Video Games,CA,failed,25000.0,6722.00,CAD,2013-09-26 19:22:52,2013-11-05,57,not_successful,1,0,6526.750000,0,1,0.268880,24273.839631

In [46]:
dfvideogames2.describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,1.147900e+04,1.147900e+04,1.147900e+04,11479.000000,11479.000000,11479.000000,1.147900e+04,11479.000000,11479.000000,11479.000000,1.147900e+04
mean,1.070665e+09,5.238376e+04,1.843213e+04,379.099138,0.791097,0.208903,1.776607e+04,0.663560,0.336440,6.833502,4.958943e+04
std,6.186688e+08,1.581232e+05,1.470645e+05,2516.426721,0.406543,0.406543,1.501842e+05,0.472512,0.472512,424.145640,1.452716e+05
min,1.886670e+05,1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,8.918919e-02
25%,5.332566e+08,3.200000e+03,4.100000e+01,3.000000,1.000000,0.000000,3.361000e+01,0.000000,0.000000,0.004584,3.000000e+03
50%,1.066891e+09,1.000000e+04,4.340000e+02,13.000000,1.000000,0.000000,3.550000e+02,1.000000,0.000000,0.052500,1.000000e+04
75%,1.604638e+09,4.000000e+04,4.334500e+03,90.000000,1.000000,0.000000,3.741330e+03,1.000000,1.000000,0.410006,3.500610e+04
max,2.147161e+09,5.000000e+06,6.333296e+06,87142.000000,1.000000,1.000000,6.333296e+06,1.000000,1.000000,41535.010000,2.500000e+06

In [47]:
dfvideogames2.corr()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
ID,1.000000,-0.003770,-0.004230,-0.003791,-0.003924,0.003924,-0.006464,0.013796,-0.013796,0.011884,-0.009131
goal,-0.003770,1.000000,0.296750,0.251892,0.050144,-0.050144,0.282428,0.038033,-0.038033,-0.005063,0.871355
pledged,-0.004230,0.296750,1.000000,0.916121,-0.195070,0.195070,0.989827,0.039769,-0.039769,0.001782,0.314771
backers,-0.003791,0.251892,0.916121,1.000000,-0.239199,0.239199,0.924406,0.036692,-0.036692,0.004503,0.283082
not_successful,-0.003924,0.050144,-0.195070,-0.239199,1.000000,-1.000000,-0.186783,-0.039814,0.039814,-0.030939,0.049186
successful,0.003924,-0.050144,0.195070,0.239199,-1.000000,1.000000,0.186783,0.039814,-0.039814,0.030939,-0.049186
usd_pledged,-0.006464,0.282428,0.989827,0.924406,-0.186783,0.186783,1.000000,0.045172,-0.045172,0.001787,0.321528
USD,0.013796,0.038033,0.039769,0.036692,-0.039814,0.039814,0.045172,1.000000,-1.000000,0.002715,0.068412
not_USD,-0.013796,-0.038033,-0.039769,-0.036692,0.039814,-0.039814,-0.045172,-1.000000,1.000000,-0.002715,-0.068412
ratio,0.011884,-0.005063,0.001782,0.004503,-0.030939,0.030939,0.001787,0.002715,-0.002715,1.000000,-0.005212
usd_goal,-0.009131,0.871355,0.314771,0.283082,0.049186,-0.049186,0.321528,0.068412,-0.068412,-0.005212,1.000000

In [48]:
dfvideogames2[dfvideogames2['successful']==1].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,2.398000e+03,2.398000e+03,2.398000e+03,2398.000000,2398.0,2398.0,2.398000e+03,2398.000000,2398.000000,2398.000000,2.398000e+03
mean,1.075389e+09,3.695479e+04,7.425615e+04,1550.396997,0.0,1.0,7.235249e+04,0.700167,0.299833,32.368628,3.568534e+04
std,6.145491e+08,1.183519e+05,3.135701e+05,5310.569968,0.0,0.0,3.211875e+05,0.458280,0.458280,927.696947,1.230581e+05
min,1.058397e+06,1.000000e+00,3.000000e+00,1.000000,0.0,1.0,0.000000e+00,0.000000,0.000000,1.000000,8.918919e-02
25%,5.380320e+08,1.500000e+03,2.783767e+03,68.000000,0.0,1.0,1.961463e+03,0.000000,0.000000,1.100115,1.000000e+03
50%,1.088288e+09,7.500000e+03,1.118326e+04,282.500000,0.0,1.0,9.790830e+03,1.000000,0.000000,1.328159,6.000000e+03
75%,1.595449e+09,2.500000e+04,4.173957e+04,1123.500000,0.0,1.0,3.651136e+04,1.000000,1.000000,2.124136,2.346325e+04
max,2.147161e+09,2.000000e+06,6.333296e+06,87142.000000,0.0,1.0,6.333296e+06,1.000000,1.000000,41535.010000,2.003273e+06

In [49]:
result = sm.ols(formula='successful ~ usd_goal + usd_pledged + backers + ratio  + USD - 1', data=dfvideogames2).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.219
Model:                            OLS   Adj. R-squared:                  0.218
Method:                 Least Squares   F-statistic:                     642.6
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:51   Log-Likelihood:                -5883.7
No. Observations:               11479   AIC:                         1.178e+04
Df Residuals:                   11474   BIC:                         1.181e+04
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
usd_goal    -2.194e-07   2.72e-08     -8.062      0.000   -2.73e-07   -1.66e-07
usd_pledged -6.596e-07   6.66e-08     -9.910      0.000    -7.9e-07   -5.29e-07
backers      8.075e-05   3.92e-06     20.593      0.000    7.31e-05    8.84e-05
ratio        2.917e-05   8.89e-06      3.281      0.001    1.17e-05    4.66e-05
USD             0.2116      0.005     43.424      0.000       0.202       0.221
==============================================================================
Omnibus:                     1982.144   Durbin-Watson:                   1.938
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3474.686
Skew:                           1.116   Prob(JB):                         0.00
Kurtosis:                       4.512   Cond. No.                     2.28e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.28e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [50]:
result = sm.ols(formula='successful ~ usd_goal + usd_pledged + backers + ratio  + USD + usd_pledged*backers + ratio*backers - 1', data=dfvideogames2).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.268
Model:                            OLS   Adj. R-squared:                  0.268
Method:                 Least Squares   F-statistic:                     601.4
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:52   Log-Likelihood:                -5506.5
No. Observations:               11479   AIC:                         1.103e+04
Df Residuals:                   11472   BIC:                         1.108e+04
Df Model:                           7
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
usd_goal            -3.393e-07   2.67e-08    -12.714      0.000   -3.92e-07   -2.87e-07
usd_pledged          4.681e-07   7.63e-08      6.138      0.000    3.19e-07    6.18e-07
backers              9.828e-05   3.85e-06     25.552      0.000    9.07e-05       0.000
ratio                 9.76e-05    2.2e-05      4.428      0.000    5.44e-05       0.000
USD                     0.1981      0.005     41.779      0.000       0.189       0.207
usd_pledged:backers -2.713e-11   9.81e-13    -27.657      0.000   -2.91e-11   -2.52e-11
ratio:backers        -5.12e-08   1.49e-08     -3.445      0.001   -8.03e-08   -2.21e-08
==============================================================================
Omnibus:                     2287.864   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3984.648
Skew:                           1.306   Prob(JB):                         0.00
Kurtosis:                       4.226   Cond. No.                     1.10e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.1e+10. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## Tabletop Games (Category under Games)

In [51]:
dftablegames = df
dftablegames = dftablegames.drop(dftablegames[dftablegames['category']!='Tabletop Games'].index)
dftablegames.head()

,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,state_recat,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
14,62304,sinbin trivia,Games,Tabletop Games,GB,failed,65000.0,11.0,GBP,2015-10-07 10:27:00,2015-11-05 23:39:00,2,not_successful,1,0,16.678594,0,1,0.000169,98555.330250
21,126581,Educational Online Trading Card Game,Games,Tabletop Games,US,failed,4000.0,20.0,USD,2010-06-16 01:34:04,2010-08-02,2,not_successful,1,0,20.000000,1,0,0.005000,4000.000000
69,401060,NODE - Ask meaningful questions,Games,Tabletop Games,DE,successful,3000.0,3442.0,EUR,2016-11-14 21:58:28,2016-12-11,139,successful,0,1,65.140000,0,1,1.147333,56.775131
151,885958,Wilderness Empires Game,Games,Tabletop Games,US,successful,5000.0,17302.0,USD,2014-11-03 03:01:00,2014-12-03 03:01:00,248,successful,0,1,17302.000000,1,0,3.460400,5000.000000
172,998541,SideQuests: Easy Adventure Modules for 5E Dung...,Games,Tabletop Games,CA,successful,1500.0,7711.0,CAD,2017-05-18 00:59:24,2017-06-27,303,successful,0,1,877.030000,0,1,5.140667,170.606277

In [52]:
dftablegames.describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,1.390900e+04,1.390900e+04,1.390900e+04,13909.000000,13909.000000,13909.000000,1.390900e+04,13909.000000,13909.000000,13909.000000,1.390900e+04
mean,1.064426e+09,1.543192e+04,3.441107e+04,430.175857,0.431735,0.568265,3.105146e+04,0.756273,0.243727,11.403084,1.619023e+04
std,6.218515e+08,4.460237e+04,2.177097e+05,2451.559581,0.495336,0.495336,2.113894e+05,0.429345,0.429345,360.522092,1.494877e+05
min,6.230400e+04,1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,4.599589e-01
25%,5.252338e+08,2.500000e+03,1.006000e+03,24.000000,0.000000,0.000000,8.070000e+02,1.000000,0.000000,0.171556,2.000000e+03
50%,1.059060e+09,7.000000e+03,4.573000e+03,97.000000,0.000000,1.000000,3.834360e+03,1.000000,0.000000,1.125000,6.038005e+03
75%,1.604255e+09,1.550000e+04,1.641100e+04,304.000000,1.000000,1.000000,1.487043e+04,1.000000,0.000000,2.920000,1.500000e+04
max,2.147389e+09,1.949000e+06,1.239314e+07,219382.000000,1.000000,1.000000,1.239314e+07,1.000000,1.000000,32843.000000,1.228400e+07

In [53]:
dftablegames.corr()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
ID,1.000000,-0.017423,0.000210,0.011640,-0.016067,0.016067,0.000460,0.001584,-0.001584,0.014297,-0.009154
goal,-0.017423,1.000000,0.132361,0.053798,0.131286,-0.131286,0.107616,-0.005564,0.005564,-0.008804,0.237590
pledged,0.000210,0.132361,1.000000,0.684635,-0.125200,0.125200,0.958835,0.017161,-0.017161,0.016132,0.028784
backers,0.011640,0.053798,0.684635,1.000000,-0.134666,0.134666,0.697218,0.036135,-0.036135,0.026544,0.012994
not_successful,-0.016067,0.131286,-0.125200,-0.134666,1.000000,-1.000000,-0.116352,-0.007580,0.007580,-0.027066,0.053589
successful,0.016067,-0.131286,0.125200,0.134666,-1.000000,1.000000,0.116352,0.007580,-0.007580,0.027066,-0.053589
usd_pledged,0.000460,0.107616,0.958835,0.697218,-0.116352,0.116352,1.000000,0.045671,-0.045671,0.016559,0.031386
USD,0.001584,-0.005564,0.017161,0.036135,-0.007580,0.007580,0.045671,1.000000,-1.000000,0.012157,-0.010596
not_USD,-0.001584,0.005564,-0.017161,-0.036135,0.007580,-0.007580,-0.045671,-1.000000,1.000000,-0.012157,0.010596
ratio,0.014297,-0.008804,0.016132,0.026544,-0.027066,0.027066,0.016559,0.012157,-0.012157,1.000000,-0.002850
usd_goal,-0.009154,0.237590,0.028784,0.012994,0.053589,-0.053589,0.031386,-0.010596,0.010596,-0.002850,1.000000

In [54]:
dftablegames[dftablegames['successful']==1].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,7.904000e+03,7904.000000,7.904000e+03,7904.000000,7904.0,7904.0,7.904000e+03,7904.000000,7904.000000,7904.000000,7904.000000
mean,1.073134e+09,10328.141574,5.816847e+04,717.926746,0.0,1.0,5.248900e+04,0.759109,0.240891,19.907910,9207.873282
std,6.209941e+08,19533.138083,2.864674e+05,3221.822674,0.0,0.0,2.784665e+05,0.427651,0.427651,478.089348,17060.862484
min,4.010600e+05,1.000000,2.000000e+00,1.000000,0.0,1.0,0.000000e+00,0.000000,0.000000,1.000000,0.459959
25%,5.341970e+08,1500.000000,4.477750e+03,102.000000,0.0,1.0,3.448902e+03,1.000000,0.000000,1.374335,1000.750000
50%,1.075728e+09,5000.000000,1.174850e+04,238.000000,0.0,1.0,1.050600e+04,1.000000,0.000000,2.469967,4475.081657
75%,1.618766e+09,11000.000000,3.401150e+04,618.000000,0.0,1.0,3.031118e+04,1.000000,0.000000,5.613058,10000.000000
max,2.147389e+09,500000.000000,1.239314e+07,219382.000000,0.0,1.0,1.239314e+07,1.000000,1.000000,32843.000000,500000.000000

In [55]:
result = sm.ols(formula='successful ~ backers + USD - 1', data=dftablegames).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.445
Model:                            OLS   Adj. R-squared:                  0.445
Method:                 Least Squares   F-statistic:                     5570.
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:53   Log-Likelihood:                -11714.
No. Observations:               13909   AIC:                         2.343e+04
Df Residuals:                   13907   BIC:                         2.345e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
backers     3.334e-05   1.94e-06     17.174      0.000    2.95e-05    3.71e-05
USD            0.5544      0.006     99.780      0.000       0.543       0.565
==============================================================================
Omnibus:                      286.241   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              408.957
Skew:                          -0.238   Prob(JB):                     1.57e-89
Kurtosis:                       3.692   Cond. No.                     2.90e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.9e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [56]:
result = sm.ols(formula='successful ~ backers + USD + backers*USD - 1', data=dftablegames).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.471
Model:                            OLS   Adj. R-squared:                  0.471
Method:                 Least Squares   F-statistic:                     4123.
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:54   Log-Likelihood:                -11381.
No. Observations:               13909   AIC:                         2.277e+04
Df Residuals:                   13906   BIC:                         2.279e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
backers         0.0003   1.01e-05     28.947      0.000       0.000       0.000
USD             0.5589      0.005    102.976      0.000       0.548       0.570
backers:USD    -0.0003   1.03e-05    -26.115      0.000      -0.000      -0.000
==============================================================================
Omnibus:                     1593.988   Durbin-Watson:                   1.920
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7052.196
Skew:                          -0.491   Prob(JB):                         0.00
Kurtosis:                       6.347   Cond. No.                     4.06e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.06e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## PRODUCT DESIGN (Category under Design)

In [57]:
dfproductdesign = df
dfproductdesign = dfproductdesign.drop(dfproductdesign[dfproductdesign['category']!='Product Design'].index)
dfproductdesign.head()

,ID,name,main_category,category,country,state,goal,pledged,currency,launched,deadline,backers,state_recat,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
41,277920,EveryGirl InBin,Design,Product Design,AU,failed,150000.0,590.0,AUD,2015-09-28 22:26:53,2015-11-27,4,not_successful,1,0,414.52,0,1,0.003933,105386.440678
54,326455,Clutch Lead Holder,Design,Product Design,US,successful,5500.0,19300.0,USD,2012-06-23 00:01:44,2012-07-23,402,successful,0,1,19300.00,1,0,3.509091,5500.000000
77,452247,SooperCrapz - DIY vinyl art toys,Design,Product Design,GB,failed,33200.0,567.0,GBP,2017-10-03 22:06:44,2017-11-09,9,not_successful,1,0,343.61,0,1,0.017078,20119.668430
87,518181,SPREADEM Bedding: Pool Print,Design,Product Design,AU,failed,12000.0,7334.0,AUD,2015-07-17 00:00:46,2015-08-12,29,not_successful,1,0,5482.62,0,1,0.611167,8970.744478
103,618765,Awning Project,Design,Product Design,US,failed,3500.0,1066.0,USD,2014-09-10 23:59:13,2014-10-11,15,not_successful,1,0,1066.00,1,0,0.304571,3500.000000

In [58]:
dfproductdesign.describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,2.186300e+04,2.186300e+04,2.186300e+04,21863.000000,21863.000000,21863.000000,2.186300e+04,21863.000000,21863.000000,21863.000000,2.186300e+04
mean,1.075032e+09,3.502806e+04,3.188751e+04,278.993505,0.629008,0.370992,2.649326e+04,0.733431,0.266569,1.971689,3.328002e+04
std,6.201067e+08,3.600073e+05,2.599236e+05,1755.576925,0.483081,0.483081,2.422700e+05,0.442175,0.442175,14.715342,4.201740e+05
min,2.779200e+05,1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,6.119701e-01
25%,5.370840e+08,5.000000e+03,4.010000e+02,8.000000,0.000000,0.000000,3.165200e+02,0.000000,0.000000,0.033200,4.500000e+03
50%,1.072421e+09,1.250000e+04,2.701000e+03,37.000000,1.000000,0.000000,2.162000e+03,1.000000,0.000000,0.260000,1.091587e+04
75%,1.613709e+09,3.000000e+04,1.422950e+04,146.000000,1.000000,1.000000,1.144662e+04,1.000000,1.000000,1.245693,2.800000e+04
max,2.147350e+09,5.000000e+07,2.033899e+07,154926.000000,1.000000,1.000000,2.033899e+07,1.000000,1.000000,1340.900000,5.000000e+07

In [59]:
dfproductdesign.corr()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
ID,1.000000,-0.010577,0.004456,0.004380,-0.004740,0.004740,0.003353,0.017883,-0.017883,-0.006650,-0.001828
goal,-0.010577,1.000000,0.031011,0.008704,0.032500,-0.032500,0.019360,-0.011847,0.011847,-0.007018,0.835375
pledged,0.004456,0.031011,1.000000,0.741828,-0.140460,0.140460,0.935122,-0.001067,0.001067,0.257993,0.014246
backers,0.004380,0.008704,0.741828,1.000000,-0.179666,0.179666,0.763962,0.028839,-0.028839,0.351745,0.006390
not_successful,-0.004740,0.032500,-0.140460,-0.179666,1.000000,-1.000000,-0.125245,-0.001743,0.001743,-0.161622,0.032458
successful,0.004740,-0.032500,0.140460,0.179666,-1.000000,1.000000,0.125245,0.001743,-0.001743,0.161622,-0.032458
usd_pledged,0.003353,0.019360,0.935122,0.763962,-0.125245,0.125245,1.000000,0.035789,-0.035789,0.256453,0.016485
USD,0.017883,-0.011847,-0.001067,0.028839,-0.001743,0.001743,0.035789,1.000000,-1.000000,0.003936,-0.003250
not_USD,-0.017883,0.011847,0.001067,-0.028839,0.001743,-0.001743,-0.035789,-1.000000,1.000000,-0.003936,0.003250
ratio,-0.006650,-0.007018,0.257993,0.351745,-0.161622,0.161622,0.256453,0.003936,-0.003936,1.000000,-0.006325
usd_goal,-0.001828,0.835375,0.014246,0.006390,0.032458,-0.032458,0.016485,-0.003250,0.003250,-0.006325,1.000000

In [60]:
dfproductdesign[dfproductdesign['successful']==1].describe()

,ID,goal,pledged,backers,not_successful,successful,usd_pledged,USD,not_USD,ratio,usd_goal
count,8.111000e+03,8.111000e+03,8.111000e+03,8111.000000,8111.0,8111.0,8.111000e+03,8111.000000,8111.000000,8111.000000,8111.000000
mean,1.078859e+09,1.979337e+04,7.942489e+04,689.691530,0.0,1.0,6.600219e+04,0.734435,0.265565,5.068448,15522.455872
std,6.212365e+08,4.401326e+04,4.222222e+05,2833.896157,0.0,0.0,3.944263e+05,0.441661,0.441661,23.841496,29476.331162
min,3.264550e+05,1.000000e+00,5.000000e+00,1.000000,0.0,1.0,0.000000e+00,0.000000,0.000000,1.000000,0.611970
25%,5.295840e+08,3.300000e+03,6.467500e+03,81.000000,0.0,1.0,4.830000e+03,0.000000,0.000000,1.146904,2320.310252
50%,1.088101e+09,1.000000e+04,1.895900e+04,199.000000,0.0,1.0,1.538100e+04,1.000000,0.000000,1.695000,8000.000000
75%,1.617973e+09,2.000000e+04,5.111350e+04,542.000000,0.0,1.0,4.267400e+04,1.000000,1.000000,3.772483,18842.000000
max,2.147022e+09,1.400000e+06,2.033899e+07,154926.000000,0.0,1.0,2.033899e+07,1.000000,1.000000,1340.900000,1000000.000000

In [61]:
result = sm.ols(formula='successful ~ usd_pledged + backers + ratio  + USD - 1', data=dfproductdesign).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.309
Model:                            OLS   Adj. R-squared:                  0.308
Method:                 Least Squares   F-statistic:                     2439.
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:55   Log-Likelihood:                -16149.
No. Observations:               21863   AIC:                         3.231e+04
Df Residuals:                   21859   BIC:                         3.234e+04
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
usd_pledged -8.212e-08   2.19e-08     -3.747      0.000   -1.25e-07   -3.92e-08
backers      5.135e-05   3.12e-06     16.458      0.000    4.52e-05    5.75e-05
ratio           0.0043      0.000     17.355      0.000       0.004       0.005
USD             0.3496      0.004     86.221      0.000       0.342       0.358
==============================================================================
Omnibus:                     1964.057   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            12580.403
Skew:                           0.159   Prob(JB):                         0.00
Kurtosis:                       6.703   Cond. No.                     2.88e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.88e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [62]:
result = sm.ols(formula='successful ~ usd_pledged + backers + ratio  + USD + usd_pledged*backers - 1', data=dfproductdesign).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             successful   R-squared:                       0.345
Model:                            OLS   Adj. R-squared:                  0.345
Method:                 Least Squares   F-statistic:                     2302.
Date:                Sat, 14 Jul 2018   Prob (F-statistic):               0.00
Time:                        11:51:55   Log-Likelihood:                -15559.
No. Observations:               21863   AIC:                         3.113e+04
Df Residuals:                   21858   BIC:                         3.117e+04
Df Model:                           5
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
usd_pledged          6.733e-07   3.04e-08     22.133      0.000    6.14e-07    7.33e-07
backers              8.958e-05   3.23e-06     27.740      0.000    8.33e-05    9.59e-05
ratio                   0.0031      0.000     12.650      0.000       0.003       0.004
USD                     0.3234      0.004     80.493      0.000       0.315       0.331
usd_pledged:backers -1.615e-11   4.64e-13    -34.830      0.000   -1.71e-11   -1.52e-11
==============================================================================
Omnibus:                      818.381   Durbin-Watson:                   1.934
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              965.966
Skew:                           0.446   Prob(JB):                    1.75e-210
Kurtosis:                       3.515   Cond. No.                     1.95e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.95e+10. This might indicate that there are
strong multicollinearity or other numerical problems.
"""